### ISSUE TITLE
CounterfactualMethod printer broken?

### ISSUE THREAD

**Issue by mb706** [dandls/counterfactuals#37]
Following the steps from the intro vignette, but then printing the `"CounterfactualMethod"` object:
```r
data(german, package = "rchallenge")
credit = german[, c("duration", "amount", "purpose", "age", "employment_duration", "housing", "number_credits", "credit_risk")]

set.seed(20210816)
rf = randomForest::randomForest(credit_risk ~ ., data = credit[-998L,])

predictor = iml::Predictor$new(rf, type = "prob")
x_interest = credit[998L, ]

moc_classif = MOCClassif$new(
  predictor, epsilon = 0, fixed_features = c("age", "employment_duration"),
  quiet = TRUE, termination_crit = "genstag", n_generations = 10L
)

moc_classif
```
gives the output
```
Counterfactual explanation method:  MOCClassif 
Parameters:
 - epsilon:  0 
 - fixed_features:  age employment_duration 
 - init_strategy:  icecurve 
 - k:  1 
 - lower:  
 - max_changed:  
 - mu:  20 
 - termination_crit:  genstag 
 - n_generations:  10 
 - p_mut:  0.73 
 - p_mut_gen:  0.5 
 - p_mut_use_orig:  0.4 
 - p_rec:  0.71 
 - p_rec_gen:  0.62 
 - upper:  - weights:  
```
* the `-upper:  - weights:` looks unintentional
* one could also put `lower` and `upper` right next to each other
* are empty entries like `lower:` and `max_changed:` deliberate?
